Repository spring-projects/spring-batch, pull requests merged in 2020-03, with the labels that each got.

#748 Update schema-appendix.adoc to fix wrong names
  spring-batch-docs/asciidoc/schema-appendix.adoc
Labels: has: backports, in: documentation, pr-for: bug

#3679 fix documentation of JobExecutionNotRunningException
  spring-batch-core/src/main/java/org/springframework/batch/core/launch/JobExecutionNotRunningException.java
Labels: in: documentation, pr-for: bug

#3682 Fix constructor of JsonItemReader to call setExecutionContextName()
  spring-batch-infrastructure/src/main/java/org/springframework/batch/item/json/JsonItemReader.java
  spring-batch-infrastructure/src/test/java/org/springframework/batch/item/json/JsonItemReaderTests.java
Labels: in: infrastructure, pr-for: bug

#3687 Updated spring-doc-resources version
  build.gradle
Labels: in: documentation, pr-for: enhancement, type: task
