Repository spring-projects/spring-batch, pull requests merged in 2020-05, with the labels that each got.

#3710 Improve performance in JdbcStepExecutionDao
  spring-batch-core/src/main/java/org/springframework/batch/core/repository/dao/JdbcStepExecutionDao.java
Labels: has: backports, in: core, pr-for: enhancement, theme: performance

#3711 Support microsecond accuracy for MySQL
  spring-batch-core/src/main/resources/org/springframework/batch/core/migration/4.3/migration-mysql.sql
  spring-batch-core/src/main/resources/org/springframework/batch/core/schema-mysql.sql
Labels: in: core, pr-for: enhancement

#3703 Upgrade versions of Asciidoctor
  build.gradle
Labels: in: documentation, type: task

#3696 [#3643] Fixing documentation typo
  spring-batch-docs/asciidoc/common-patterns.adoc
Labels: in: documentation, pr-for: bug

#3702 Fixing Misleading Java Code in documentation
  spring-batch-docs/asciidoc/spring-batch-integration.adoc
Labels: in: documentation, pr-for: bug
