Repository spring-projects/spring-batch, pull requests merged in 2025-07, with the labels that each got.

#4895 Add project icon for JetBrains products
  .gitignore
  .idea/icon.svg
Labels: type: task

#4901 Polish code block style and fix typo in whatsnew.adoc
  spring-batch-docs/modules/ROOT/pages/whatsnew.adoc
Labels: pr-for: enhancement, in: documentation, for: backport-to-5.2.x

#4822 Correct comment in test examples
  spring-batch-samples/src/test/java/org/springframework/batch/samples/chunking/RemoteChunkingJobFunctionalTests.java
Labels: pr-for: enhancement, status: feedback-provided

#4803 Use typesafe variant of `ctx::getBean` instead
  spring-batch-core/src/main/java/org/springframework/batch/core/configuration/support/DefaultJobLoader.java
  spring-batch-core/src/main/java/org/springframework/batch/core/configuration/xml/CoreNamespacePostProcessor.java
  spring-batch-core/src/main/java/org/springframework/batch/core/launch/support/CommandLineJobRunner.java
  spring-batch-core/src/test/java/org/springframework/batch/core/SpringBeanJobTests.java
  spring-batch-core/src/test/java/org/springframework/batch/core/configuration/annotation/JobScopeConfigurationTests.java
  spring-batch-core/src/test/java/org/springframework/batch/core/configuration/annotation/StepScopeConfigurationTests.java
  spring-batch-core/src/test/java/org/springframework/batch/core/configuration/xml/PartitionStepParserTests.java
  spring-batch-core/src/test/java/org/springframework/batch/core/configuration/xml/StepListenerInStepParserTests.java
  spring-batch-core/src/test/java/org/springframework/batch/core/configuration/xml/StepNameTests.java
  spring-batch-core/src/test/java/org/springframework/batch/core/configuration/xml/StepParserTests.java
  spring-batch-core/src/test/java/org/springframework/batch/core/configuration/xml/TaskletStepAllowStartIfCompleteTests.java
  spring-batch-core/src/test/java/org/springframework/batch/core/repository/dao/jdbc/JdbcStepExecutionDaoTests.java
  spring-batch-core/src/test/java/org/springframework/batch/core/step/item/FaultTolerantExceptionClassesTests.java
  spring-batch-infrastructure/src/test/java/org/springframework/batch/item/database/AbstractDatabaseItemStreamItemReaderTests.java
  spring-batch-infrastructure/src/test/java/org/springframework/batch/item/database/builder/JdbcBatchItemWriterBuilderTests.java
  spring-batch-infrastructure/src/test/java/org/springframework/batch/item/database/builder/JdbcCursorItemReaderBuilderTests.java
  spring-batch-infrastructure/src/test/java/org/springframework/batch/item/database/builder/JdbcPagingItemReaderBuilderTests.java
  spring-batch-infrastructure/src/test/java/org/springframework/batch/item/database/builder/JpaCursorItemReaderBuilderTests.java
  spring-batch-infrastructure/src/test/java/org/springframework/batch/item/database/builder/JpaPagingItemReaderBuilderTests.java
  spring-batch-infrastructure/src/test/java/org/springframework/batch/repeat/jms/SynchronousTests.java
  spring-batch-test/src/test/java/org/springframework/batch/test/SampleStepTests.java
Labels: pr-for: enhancement, for: backport-to-5.2.x
